### ISSUE TITLE
Screenshots should have a transparent background

### ISSUE THREAD

**Issue by danrabbit** [thejambi/psnotes#11]
Hey thanks for submitting your app to AppCenter. Sorry to say, I've marked the latest release as needs fixing for the following reason:

Screenshots should contain a transparent background. You can do this easily with the built in screenshot tool and the "Grab the current window" mode.

**Comment by thejambi** [comment]
Sweet, will replace the screenshot tonight. Where is the documentation on things like that? (I was just getting by on referencing others' repos)

**Comment by danrabbit** [comment]
I don't believe there is currently documentation regarding screenshots. Sorry for the inconvenience there! I'm happy to answer any questions you might have though. We're still putting together much of the documentation regarding publishing in AppCenter Dashboard as the process evolves. I appreciate your patience here! :)

**Comment by thejambi** [comment]
No problem, I'm happy to try it out!
