### ISSUE TITLE
Improve style?

### ISSUE THREAD

**Issue by peteruithoven** [thejambi/psnotes#15]
I really like the functionality of this app, but I think the style could be improved. 

For inspiration I looked at:
## nvAlt2
![nvAlt2 screenshot](https://user-images.githubusercontent.com/523210/27748240-ef00247c-5dce-11e7-8267-def47be0cd01.jpg)
## Quilter
![quilter screenshot](https://user-images.githubusercontent.com/523210/27748247-f4a1bb84-5dce-11e7-859b-7b73b62d6c5f.png)
## Scratch
![scratch screenshot](https://user-images.githubusercontent.com/523210/27748250-f9e59066-5dce-11e7-8edb-6801902e2ba7.png)
## Simplenote
![Simplenote screenshot](https://user-images.githubusercontent.com/523210/27748252-fc577e4a-5dce-11e7-9ad6-77c5da05ea72.png)

**Comment by peteruithoven** [comment]
https://github.com/thejambi/psnotes/pull/16 contains some changes that makes it look like:
![screenshot from 2017-06-30 19 58 57](https://user-images.githubusercontent.com/523210/27748724-be47cd24-5dd0-11e7-864c-e68f063b6f98.png)

**Comment by thejambi** [comment]
So far I've focused more on fine tuning the feel of the editor itself - margins, line spacing, etc and that's made a big difference. Good idea to make the rest look a bit better!

**Comment by thejambi** [comment]
I updated with your changes here and with a bunch of work on performance updates. Would you mind updating to the latest code and trying it out and making sure your files are always still getting saved?

**Comment by peteruithoven** [comment]
I'm glad you like the changes, thanks for merging. I've tried the master branch and it seems to still work.
