### ISSUE TITLE
AppCenter: increment changelog, don't overwrite it

### ISSUE THREAD

**Issue by codygarver** [thejambi/psnotes#17]
Hi, in the latest version of PS Notes submitted to the elementary OS AppCenter, you overwrote the previous `debian/changelog` entry for `0.17` with `0.18`.

Instead, a new changelog entry should've been added. An easy way to do this (if there wasn't already an existing entry) is `dch -v 0.18`.

I'm not going to reject your app because of this, but for future reference please increment the changelog instead of overwriting it.

**Comment by thejambi** [comment]
Got the dch command set up for next time. Thanks!
