### ISSUE TITLE
subfolders in notebooks

### ISSUE THREAD

**Issue by bexelbie** [thejambi/psnotes#2]
(I realize this is not the most current code, I just wanted to file the suggestion)

I use an app called plaintext on iOS that allows me to have subfolders.  If psnotes would support that I could have them share a dropbox location.

I haven't even tried to look at the code for what this would take to support.

**Comment by thejambi** [comment]
As a workaround for this, you can add multiple folders to PSNotes as additional "notebooks" and it will work.

**Comment by thejambi** [comment]
I just committed some changes. Subfolders should show up and work now!

**Comment by thejambi** [comment]
Unfortunately I am unable to build a deb package file (at least, one that includes the icon and launcher as it normally does) so I will not be updating the PPA.
